add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "claude"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N](bold orange) >>>"
success_symbol = '[➜](bold bright-green)'
error_symbol = '[➜](bold bright-red)'

[directory]
style = "bold bright-blue"
truncation_length = 3
truncate_to_repo = false

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bright-cyan"
symbol = " "

[git_status]
style = "bright-yellow"

[aws]
format = '[$symbol(profile: "$profile" )(\($region\) )]($style)'
disabled = true
style = 'bold bright-blue'
symbol = ""

[golang]
disabled = true
format = '[ ](bold bright-cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
style = "bright-green"
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "bright-green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true
style = "bright-blue"

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bright-yellow"
symbol = " "

[nodejs]
disabled = true
style = "bright-green"

[package]
disabled = true

[cmd_duration]
style = "bright-yellow"

[time]
disabled = false
style = "bright-white"

# Custom Claude palette matching your terminal colors
[palettes.claude]
# Basic colors (much brighter to match your theme)
black = "#1f1e1d"
red = "#FF9B9B"
green = "#C8FF9B"
yellow = "#FFDB9B"
blue = "#9BC8FF"
purple = "#E89BFF"
cyan = "#9BFFE8"
white = "#FFFFFF"

# Bright variants
bright-black = "#6B6A67"
bright-red = "#FFB8B8"
bright-green = "#D8FFB8"
bright-yellow = "#FFEBB8"
bright-blue = "#B8D8FF"
bright-purple = "#F8B8FF"
bright-cyan = "#B8FFF8"
bright-white = "#FFFFFF"

# Claude theme colors
orange = "#CC785C"
bg = "#262624"
bg-dark = "#1f1e1d"

# Semantic colors for better readability
text = "#FFFFFF"
subtext = "#E8E5E0"
overlay = "#C8C5C0"
surface = "#6B6A67"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

